language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

branches:
  only:
    - master

matrix:
  allow_failures:
    - node_js: 0.12

before_script:
  - npm install -g grunt-cli
  - grunt jshint
